appName: hisbook-back
replicaCount: 1

namespace: hisbook-back

image:
  name: jeniel/hisbook-back
  tag: defd520-backend

host:
#  name: hisbookback.bata.local
   name: back.192.168.254.160.nip.io
onPrem: true
