appName: hisbook-back
replicaCount: 1

namespace: hisbook-back

image:
  name: acemcbmis/hisbook-back
  tag:  75b212f-prod

host:
#  name: hisbookback.bata.local
   name: back.192.168.254.160.nip.io
onPrem: true
